language: c

script:
  #- HelloWorld
  #this one is for the project
  - bison -t -d Parser.y
  - flex Lexer.l
  - gcc Parser.tab.c lex.yy.c -o hello -lm
  - cd Unit-test-files
  - gcc -o check test.c
